apiVersion: apps/v1
kind: Deployment
metadata:
    name: learning-tower-web
spec:
    selector:
        matchLabels:
            run: learning-tower-web
    replicas: 2
    template:
        metadata:
            labels:
                run: learning-tower-web
        spec:
            containers:
            - name: learning-tower-web
              image: gulbrand/learning-tower-web
              ports:
              - containerPort: 8000
