apiVersion: v1
kind: Service
metadata:
    name: learning-tower-web
    labels:
        run: learning-tower-web
spec:
    ports:
    - port: 8000
      protocol: TCP
    selector:
        run: learning-tower-web
